---
title: "R Notebook"
output: html_notebook
---

packages
```{r}
library(tidyverse)
library(leaflet) 
library(magrittr)
library(stringr)
```

Read in data
```{r}
download.file("https://opendata.socrata.com/api/views/ddym-zvjk/rows.csv?accessType=DOWNLOAD",destfile="data.csv",method="libcurl")

# Base R
# starbucks1 <- read.csv("data.csv")

# readr
starbucks <- read_csv("data.csv")

# is this needed? as_tibble(starbucks)

# rename(starbucks, `StoreNumber` =  `Store Number` )

#Make State a factor for later on
#starbucks$State.f <- factor(starbucks$State)
#is.factor(starbucks$State.f)

class(starbucks)

#View(starbucks2)

starbucks


```

Let's now subset it for CA
```{r}

# Base R
# starbucks <- starbucks1[ which(starbucks1$State=='VA' & starbucks1$Country== 'US'), ]

# Dplyr
# Without pipes
# starbucks_MO <- filter(starbucks, Country== 'US', State=='VA')

starbucks_DC <- starbucks %>%
  filter(Country== 'US', State=='DC')%>% 
  select(Brand, `Store Number`, `Ownership Type`, City,	State,	Zip, Country, Coordinates,	Latitude,	Longitude, Name)

```

```{r}

leaflet() %>% addTiles() %>% setView(-77.076723, 38.940448, zoom = 12) %>% 

addMarkers(data = starbucks_DC, lat = ~ Latitude, lng = ~ Longitude, popup = starbucks_DC$Name)

```

```{r}
# Base R
# starbucks1 <- read.csv("data.csv")

# Dplyr
starbucks_R_C_P <- read_csv("data/starbucks_R_C_P.csv")

# rename(starbucks_R_C_P, StoreNumber = `Store Number`)

class(starbucks_R_C_P)

#View(starbucks2)

```
Excel
```{r}
starbucks_DC_R_C_P <- starbucks_DC %>%
  left_join(starbucks_R_C_P, by = 'Store Number')

#rename(starbucks_R_C_P, StoreNumber = `Store Number`)

starbucks_DC_R_C_P$`Ownership Type.f` <- factor(starbucks_DC_R_C_P$`Ownership Type`)
is.factor(starbucks_DC_R_C_P$`Ownership Type.f`)

starbucks_DC_R_C_P

```



```{r}
ggplot(data = starbucks_DC_R_C_P) +
  geom_bar(mapping = aes(x = `Ownership Type.f`))
```

```{r}

ggplot(data = starbucks) +
  geom_bar(mapping = aes(x = `State.f`))
```

```{r}

options(scipen=10000)

ggplot(starbucks_DC_R_C_P, aes(P)) + 
  geom_histogram()

```

```{r}

options(scipen=10000)

ggplot(starbucks_DC_R_C_P, aes(x=C, y=`Ownership Type.f`)) + geom_point()

```

